### ISSUE TITLE
YAML output unquotes timestamps

### ISSUE THREAD

**Issue by mweinelt** [remarshal-project/remarshal#52]
Hey, I found one more regression that affects us over in nixpkgs.

When converting from JSON to YAML, a string that holds a timestamp (e.g. hh:mm:ss) will be represented by a bare, unquoted string in YAML. This leads e.g. PyYAML to interpret it and read it as seconds since the day started.

```sh
$ cat test.json 
{
  "time": "22:30:00"
}
$ json2yaml test.json test.yaml
$ cat test.yaml
time: 22:30:00
$ python3
Python 3.12.7 (main, Oct  1 2024, 02:05:46) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.safe_load(open("test.yaml"))
{'time': 81000}
>>> 
```

This is probably another regression from moving to ruamel-yaml. I hope there is a knob to tune this library further in the right direction.

Thank you!

**Comment by dbohdan** [comment]
Thanks for the report. This is unfortunate, and it makes me wonder how many hidden regressions are left. I had doubts about this migration. Now I am thinking that perhaps it was a mistake. I'll have to investigate switching back to PyYAML with [perlpunk/pyyaml-core](https://github.com/perlpunk/pyyaml-core) for YAML 1.2. (A return to YAML 1.1 is not an option I am considering. Too much configuration is in 1.2.)

The fix will probably have to wait a few days. I can't work on it right now, and it may take longer if the solution ends up being a switch libraries.

**Comment by dbohdan** [comment]
The same applies to `on` and `off`. As part of addressing the infamous Norway problem, YAML 1.2 stopped treating `on` and `off` as booleans. Now they don't need quoting.
